spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/coursedesign
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: /gtl
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:T:\\gtl\
mybatis:
  type-aliases-package: com.hnu.dbserver.entity
server:
  port: 8080


